---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../base

patches:
  - path: add_cluster_name_to_args.yaml
    target:
      group: apps
      kind: Deployment
      name: aws-load-balancer-controller
      version: v1
