aws_region        = "us-east-1"
api_name          = "Shush-SherlockAPI"
exported_api_file = "./templates/sherlock-api-export.json"
stage_name        = "v1"
cognito_userpoolname = "sherlock-userpool"
sherlock_api_oauth_domain = "360-api"
sherlock_api_client = "360-client"
sherlock_api_url= "" ## need to update the url
oauth_domain = "360-api"