---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - crd.yaml
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - deployment.yaml
  - pod-disruption-budget.yaml
  - role-binding.yaml
  - role.yaml
  - service-account.yaml
  - service.yaml
  - flow-schema.yaml
  - node-pool.yaml
  - ec2-node-class.yaml
