apiVersion: v1
kind: ServiceAccount
metadata:
  name: hudson-sa
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sherlock
  name: sherlock
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: sherlock
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sherlock
    spec:
      serviceAccountName: hudson-sa
      containers:
        - name: sherlock
          image: us-central1-docker.pkg.dev/sherlock-004/hudson/sherlockapi:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: "1000m"
              memory: "200Mi"
            limits:
              cpu: "1500m"
              memory: "500Mi"
          # Uncomment and configure if you need environment variables
          # env:
          #   - name: MY_ENV_VAR
          #     value: "some_value"
---
apiVersion: v1
kind: Service
metadata:
  name: sherlock-service
spec:
  type: ClusterIP
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: sherlock
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sherlock
  labels:
    app: sherlock
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sherlock-service
                port:
                  number: 8081

