---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: karpenter
  - path: ec2nodeclass.yaml
    target:
      group: karpenter.k8s.aws
      version: v1beta1
      kind: EC2NodeClass
      name: default
