apiVersion: v1
kind: ServiceAccount
metadata:
  name: hudson-sa
---
apiVersion: v1
kind: Service
metadata:
  name: hss-lab-service
spec:
  type: ClusterIP
  ports:
    - port: 50058
      targetPort: 50058
      protocol: TCP
      name: http
  selector:
    app: hss-lab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hss-lab
  name: hss-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hss-lab
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hss-lab
    spec:
      serviceAccountName: hudson-sa
      containers:
        - image: us-central1-docker.pkg.dev/sherlock-003/shushdeployment-lla/hss-lab:latest
          name: hss-lab
          imagePullPolicy: Always
          ports:
            - containerPort: 50058
          resources:
            requests:
              cpu: 1
              memory: 200Mi
            limits:
              cpu: 2
              memory: 500Mi
